import { GameStats } from '../modules/games/types/games.types.js'

export const STATES: GameStats[] = [
  {
    id: -60,
    name: 'minecraft',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: false,
  },
  {
    id: 730,
    name: 'Counter-Strike 2',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: true,
  },
  {
    id: -20,
    name: 'Fortnite',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: true,
  },
  {
    id: 252950,
    name: 'Rocket League',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: true,
  },
  {
    id: -50,
    name: 'League of Legends',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: false,
  },
  {
    id: 291550,
    name: 'Brawlhalla',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: true,
  },
  {
    id: 427520,
    name: 'Factorio',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 526870,
    name: 'Satisfactory',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: -10,
    name: 'Valorant',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: true,
  },
  {
    id: 105600,
    name: 'terraria',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 365670,
    name: 'Blender',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: false,
  },
  {
    id: 108600,
    name: 'Project Zomboid',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: false,
  },
  {
    id: 218620,
    name: 'Payday 2',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: false,
  },
  {
    id: 361420,
    name: 'ASTRONEER',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 1030300,
    name: 'Silksong',
    isLoved: true,
    isFavorite: true,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 250900,
    name: 'The Binding of Isaac: Rebirth',
    isLoved: true,
    isFavorite: true,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 2807960,
    name: 'Battlefield™ 6',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: false,
  },
  {
    id: 979120,
    name: 'Autonauts',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 813780,
    name: 'Age of Empires II',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: false,
  },
  {
    id: 2162800,
    name: 'shapez 2 - Factory',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 814380,
    name: 'Sekiro™: Shadows Die Twice',
    isLoved: true,
    isFavorite: true,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 620,
    name: 'Portal 2',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 255710,
    name: 'Cities Skylines',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: false,
  },
  {
    id: 1106840,
    name: 'Hydroneer',
    isLoved: false,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 275850,
    name: "No Man's Sky",
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: false,
  },
  {
    id: 413150,
    name: 'stardew valley',
    isLoved: false,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 3357650,
    name: 'PRAGMATA',
    isLoved: true,
    isFavorite: true,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 367520,
    name: 'Hollow Knight',
    isLoved: false,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 4197610,
    name: 'Librarian: Tidy Up the Arcane Library!',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 3812600,
    name: 'ReStory: Chill Electronics Repairs',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 1332010,
    name: 'Stray',
    isLoved: true,
    isFavorite: true,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 220240,
    name: 'Far cry 3',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: false,
  },
  {
    id: 433340,
    name: 'Slime Rancher',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: false,
  },
  {
    id: 3846120,
    name: 'MineMogul',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: false,
  },
  {
    id: 220,
    name: 'Half-Life 2',
    isLoved: true,
    isFavorite: true,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 1172470,
    name: 'Apex Legends',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: false,
  },
  {
    id: 319630,
    name: 'Life is Strange™',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: false,
  },
  {
    id: 4294490,
    name: 'KOTAMON: My Sis Found A Super-Rare Card In Her Cereal Box, So I Became A Garbage Man To Find The Entire Collection And Earn $1,000,000',
    isLoved: false,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 2527500,
    name: 'MiSide',
    isLoved: true,
    isFavorite: true,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 400,
    name: 'Portal',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 3684710,
    name: 'My sexy Neighbour 2',
    isLoved: false,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 1222140,
    name: 'Detroit: Become Human',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 3981100,
    name: 'Leaf it Alone',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 698780,
    name: 'Doki Doki Literature Club',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: false,
    hasRanking: false,
  },
  {
    id: 524220,
    name: 'NieR:Automata™',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 1382070,
    name: 'Viewfinder',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 460950,
    name: 'Katana ZERO',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 356040,
    name: 'Sheltered',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 3244220,
    name: 'A Game About Digging A Hole™',
    isLoved: false,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 683320,
    name: 'GRIS',
    isLoved: true,
    isFavorite: true,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 4512570,
    name: 'A Game About Chopping Trees',
    isLoved: false,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 4026250,
    name: 'Project P.I.T.T.',
    isLoved: false,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 1334590,
    name: 'Furry Love',
    isLoved: false,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 678960,
    name: 'CODE VEIN',
    isLoved: false,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 3767740,
    name: 'Outhold',
    isLoved: false,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 12200,
    name: 'Bully: Scholarship Edition',
    isLoved: true,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
  {
    id: 409720,
    name: 'BioShock 2 Remastered',
    isLoved: false,
    isFavorite: false,
    trackingPlatinum: true,
    hasRanking: false,
  },
]
